DROP TABLE IF EXISTS TA_MUSICSTYLE;
CREATE TABLE TA_MUSICSTYLE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(32) NOT NULL,
    activado BOOLEAN
);

DROP TABLE IF EXISTS TA_SURVEYMUSICFAV;
CREATE TABLE TA_SURVEYMUSICFAV (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    fecha_creacion TIMESTAMP,
    email VARCHAR(254) NOT NULL,
    id_musicstyle INTEGER NOT NULL
);

ALTER TABLE TA_SURVEYMUSICFAV ADD FOREING KEY (id_musicstyle) REFERENCES TA_MUSICSTYLE(id);
ALTER TABLE TA_SURVEYMUSICFAV ALTER COLUMN fecha_creacion SET DEFAULT CURRENT_TIMESTAMP;